### ISSUE TITLE
Scanning in Motion

### ISSUE THREAD

**Issue by hhuumm** [afriscic/BarcodeScanning.Native.Maui#13]
Hello,

I'm using your package and demo for a POC. Works great relative to other solutions we have tried to use. I wanted to ask about scanning in motion. While scanning, at a very slow conveyer speed, it can pick up the codes (QR in our case). But when the speed is increased we lose the ability to recognize the barcodes. Are there fields you would recommend to adjust in order to increase the likelihood of a successful in-motion scan?

**Comment by afriscic** [comment]
Hi,

unfortunately, I don't think it would be possible to do it with this package. I think the problem is that barcodes get blurry on video feed. You can maybe try on iPhones as they have faster detection and generally better cameras than Android phones.
Maybe it would be possible with different approach, taking still images with very fast shutter speeds and further camera optimisations, bit this is out of scope for this project.

**Comment by hhuumm** [comment]
Thank you for the speedy response Afriscic! Will try and figure something out, camera quality and blur are the main issues for sure. Your app is by far the best "out of the box" scanner that's ported to MAUI, keep up the good work!
