### ISSUE TITLE
Android System.InvalidOperationException crash in CameraViewHandler.UpdateAnalyzer for 106 users (172 reports)

### ISSUE THREAD

**Issue by RyanNieburViewpoint** [afriscic/BarcodeScanning.Native.Maui#40]
Thank you for creating this library! We recently switched to it with our transition to MAUI and it has met our needs very well!

However, since using it we have seen 172 reports of the following crash in `CameraViewHandler.UpdateAnalyzer` from 106 users:

```
System.InvalidOperationException: VirtualView cannot be null here
Microsoft.Maui.Handlers.ViewHandler`2[[BarcodeScanning.CameraView, BarcodeScanning.Native.Maui, Version=1.2.4.0, Culture=neutral, PublicKeyToken=null],[BarcodeScanning.BarcodeView, BarcodeScanning.Native.Maui, Version=1.2.4.0, Culture=neutral, PublicKeyToken=null]].get_VirtualView()
BarcodeScanning.CameraViewHandler.UpdateAnalyzer()
BarcodeScanning.CameraViewHandler.Start()
Java.Lang.Thread.RunnableImplementor.Run()
Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)
Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz)
```

There is a check in `CameraViewHandler.UpdateAnalyzer` for whether VirtualView is null (`&& VirtualView is not null`) here:
https://github.com/afriscic/BarcodeScanning.Native.Maui/blob/79a14958c2c54e6caf48f476fa009739cc506dcc/BarcodeScanning.Native.Maui/Platforms/Android/CameraViewHandler.cs#L105

However, the `ViewHandler<TVirtualView, TPlatformView>.VirtualView` property throws `InvalidOperationException` if it is null:
https://github.com/dotnet/maui/blob/df5061e531656564942691ae70fbb157b6d791d3/src/Core/src/Handlers/View/ViewHandlerOfT.cs#L42

Luckily, there is also an implementation of `IViewHandler.VirtualView` in the class without that check that can be called instead:
https://github.com/afriscic/BarcodeScanning.Native.Maui/pull/39/files

Please let me know if you have any question or concerns about the pull request I have provided to address this crash!

**Comment by afriscic** [comment]
Hello. Thank you for bug report and pull request. I won't implement your PR directly but you gave me an idea how to (hopefully) fix this. MAUI is being a bit of a pain on Android because you get this exceptions on some devices that i cannot replicate on mine to test bug fixes, so I have to go blind. 
And also god forbid you do something exotic as a null check...
As i had time today i pushed a new 1.3.1 version that eliminates null check on VirtualView, and moves all usage of VirtualView properties to frame analyser where all exceptions get ignored already. Maybe not the best solution, but i hope it will be more robust as if an error occurs the frame gets closed and, hopefully, camera gets closed and everything disposed as the view closes.
If this doesn't help i think I'll need to implement your solution but also for all times VirtualView?.PropertyValue gets called, as every time there is a possibility that an exception will be thrown...
I'll leave this issue open so you can report back.

**Comment by RyanNieburViewpoint** [comment]
Great, thank you! We were also unable to repro the issue ourselves, and yeah, this does seem like a pain. We will be shipping a new version of our app with your update toward the end of next week, I will keep you updated with what we see in the wild!
